name: Build Error Pages

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Go environment
              uses: actions/setup-go@v3
              with:
                  go-version: "1.23" # You can change this to the version you need

            - name: Copy main.html to templates directory
              run: |
                  rm -rf ./error-pages/templates/*.html
                  cp main.html ./error-pages/templates/main.html

            - name: Change directory to error-page
              run: cd ./error-page || exit

            - name: Run go command to build error pages
              run: go run ./cmd/error-pages build --add-template=templates/main.html --index

            - name: Archive
              run: zip -r ./main ./../error-page.zip .

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: error-pages-static
                  path: ./error-page.zip
                  if-no-files-found: error
                  retention-days: 7

            - name: Ready to deploy
              run: |
                mkdir -p ./gh-pages/main
                cp -r ./main ./gh-pages/main
                cp ./index.html ./gh-pages/index.html
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./gh-pages
